### ISSUE TITLE
attempt to call a nil value (global 'simExtCHAI3D_start')

### ISSUE THREAD

**Issue by zhangm365** [CoppeliaRobotics/simCHAI3D#1]
I copy the v_repExtCHAI3D.dll in V-REP( 64 bits )，and it can load "CHAI3D" plugin successful. But when I start the simulation，the error happen : 
[Pioneer_p3dx@childScript:error] [string "Pioneer_p3dx@childScript"]:33: attempt to call a nil value (global 'simExtCHAI3D_start')
    stack traceback:
        [string "Pioneer_p3dx@childScript"]:33: in function 'sim_code_function_to_run'

----------------------------

How to fix it?

**Comment by Coppelia** [comment]
Hello,

try to rename those CHAI functions from e.g. simExtCHAI3D_start to simCHAI3D.start

**Comment by zhangm365** [comment]
Yes, I changed it to "simExtCHAI3D_start" to "simCHAI3D.start" in file  ...\chai3d-3.2.0\modules\V-REP\src\v_repExtCHAI3D.cpp, but when I run the demo( 02-V-REP-Pioneer.ttt ) in the V-REP, it was the same error as follows:
![image](https://user-images.githubusercontent.com/22396672/122852136-b735f100-d342-11eb-87ba-66a7723e961b.png)
---------
![image](https://user-images.githubusercontent.com/22396672/122852582-75597a80-d343-11eb-8bde-fc98d466d42d.png)
---------
![image](https://user-images.githubusercontent.com/22396672/122852646-8904e100-d343-11eb-8385-6b9a3ce86cd7.png)

**Comment by Coppelia** [comment]
simCHAI3D, not simExtCHAI3D!
Also, make sure the CHAI3D plugin was successfully loaded

**Comment by zhangm365** [comment]
Yeah，the CHAI3D plugin is successfully loaded
----------------
![image](https://user-images.githubusercontent.com/22396672/122862775-3ed82b80-d354-11eb-9f4f-2a7f2a121842.png)

But the same error :
______________
![image](https://user-images.githubusercontent.com/22396672/122863889-341e9600-d356-11eb-9436-6b8375b7b0b6.png)

**Comment by Coppelia** [comment]
Ok, so it seems you are compiling the plugin yourself. Are you using the correct plugin source? From your previous comment (_"Yes, I changed it to "simExtCHAI3D_start" to "simCHAI3D.start" in file ...\chai3d-3.2.0\modules\V-REP\src\v_repExtCHAI3D.cpp"_) it seems you are using a different source

**Comment by Coppelia** [comment]
Let's continue that discussion on the forum, as it seems you have posted there too

**Comment by zhangm365** [comment]
Yeah, I have posted the bugs in the forum. Thank your help!
